### ISSUE TITLE
What picom fork you use?

### ISSUE THREAD

**Issue by FrenzyExists** [joni22u/rofi#4]
Hey sup! Love your rofi config! Sorry for opening an issue, just had a quick question, what picom fork you use? I use Ysui's fork. Reason is because rofi's borders looks quite odd for some reason, it seems it doesn't actually render the curvature of the rofi menu for some reason

![image](https://user-images.githubusercontent.com/47986470/141009455-62452ef9-687a-4c22-bce6-b6f400198e14.png)

Here's a closer look:

![image](https://user-images.githubusercontent.com/47986470/141009569-58d75597-509b-45e1-8153-88a6f1b37f75.png)

I checked your dots, but couldn't find any specific config for rofi, and i even replaced your picom config with mine just in case, and still got that odd transparent line, so I'm assuming it has to do with my picom fork, any ideas?

**Comment by joni22u** [comment]
thank you! I use ibhagwan's fork. you need to be using rounded corners for the nicest effect. I recommend the same size as rofi. if you only want rofi to have rounded corners then add it to the picom rules.
